[build]
  publish = "_site"
  command = "deno run --allow-all npm:puppeteer browsers install chrome && deno task build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"